# This is a basic workflow that is manually triggered

name: boot_merger workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  repository_dispatch:


env:
  REPO_URL: https://github.com/rockchip-linux/rkbin
  REPO_BRANCH: master
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: 下载源码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH rkbin
        ln -sf /workdir/rkbin $GITHUB_WORKSPACE/rkbin

    - name: 开始编译固件
      id: compile
      run: |
        cd rkbin
        ./tools/burner_image_kits/make.sh rk3568
