# This is a basic workflow that is manually triggered

name: boot_merger workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/hotwlxx/rkbin
  REPO_BRANCH: master
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 开始设置编译所需环境
      run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

    # Runs a single command using the runners shell
    - name: 下载源码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH rkbin
        ln -sf /workdir/rkbin $GITHUB_WORKSPACE/rkbin

    - name: 开始编译固件
      id: compile
      run: |
        cd rkbin
        ./tools/boot_merger ../rkbin/RKBOOT/RK3568MINIALL.ini
        echo "::set-output name=status::success"
        ls -l

    - name: 检查github储存空间情况
      if: (!cancelled())
      run: df -hT

    - name: 打包项目
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: loader${{ env.FILE_DATE }}
        path: ${{ github.workspace }}
